# Default values for moss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: watsoncloudperf/pingservlet-java
  tag: latest
  pullPolicy: Always
service:
  name: http
  type: ClusterIP
  externalPort: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
hpa:
  targetCPUUtilizationPercentage: 80
ingress:
  host: 
