apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /servlet
        backend:
         serviceName: {{ template "fullname" . }}-service
         servicePort: 80
