apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ping-operator
  template:
    metadata:
      labels:
        name: ping-operator
    spec:
      serviceAccountName: ping-operator
      containers:
        - name: ping-operator
          # Replace this with the built image name
          image: watsoncloudperf/ping-operator:1.0.0
          command:
          - ping-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ping-operator"
